### ISSUE TITLE
Module-info with JDK patch version number causing problems

### ISSUE THREAD

**Issue by agentgt** [jvm-repo-rebuild/reproducible-central#113]
Apparently `module-info.class` files have the exact JDK version used to compile. When I mean exact it has even the patch version.

There must be some flag I'm missing so I figure you or someone that does reproducible builds has seen this.

My guess is why others do not see this is they are using the exact same maven docker image they released on and thus they have the exact same JDK but I released using my machine using a different patch version JDK.

You could argue that I should use a docker image to do release builds but this reliance seems deeply problematic given vendors can make different patch version numbers.

**Comment by agentgt** [comment]
Ok I figured it out but it is still a massive problem. The problem is that java records the module information of all modules.

The modules outside of the JDK are fine because we can pin those with Maven or Gradle.

But the JDK itself with reproducible-central is non-trivial because it relies on whatever the Maven docker builds choose **AND the minor version can change all the time** and thus not very reproducible.

We need a way to express and pin the exact version of the JDK docker image and not Maven.

**Comment by agentgt** [comment]
I can see the mvnBuildDocker.sh where you do:

https://github.com/jvm-repo-rebuild/reproducible-central/blob/502a1de1cd23754fb3027e8a81b93422aa3f2412/bin/includes/mvnBuildDocker.sh#L31

Ok so we use Ubuntu Jammy openjdk.

https://packages.ubuntu.com/jammy/openjdk-17-jdk

Well here is another problem even if you pin the version of ubuntu the arm64 version and amd64 version have different patch versions:

```
amd64 | 17.0.7
arm64 | 17.0.2
```

That is a problem because I have Mac that is probably using the Arm64 ubuntu image.

**Comment by agentgt** [comment]
Never mind it appears arm does pull 17.0.7 so I released on that.

I still have my concern that a docker image might change its patch version of the JDK and thus will break the build.

**Comment by hboutemy** [comment]
it's probably the first release that we try to rebuild that uses modules: I never worked on that aspect

**Comment by hboutemy** [comment]
we'll need to add new options to the rebuilding script to be able to specify (and guarantee at runtime) a precise JDK release, for these cases (unless we find a strategy to make the build not record the info)
would sdkman give us the right flexibility? Can we for example install a 17.0.1 JDK nowadays with sdkman?

**Comment by agentgt** [comment]
The problem with SDKman is I'm not sure they make any guarantees on reproducibility. In an ideal world every external binary tool (ie not easy to observe script) used to do the build needs to be reproducible.

That is if we allow access to sdkman the only JDK builds one should be able to choose are the reproducible ones. That being said I don't know of any JDK builds that are!

My guess is the safest and best option is reproducible-central provides openjdk builds that are reproducible but I don't think that is currently possible.

Since that probably is not feasible than we either standardize on Temurin aka Adoptium since they are trying to make it reproducible: https://adoptium.net/blog/2022/06/adoptium-reproducible-builds/

Ideally we would use jdk.java.net aka OpenJDK builds but they do not always offer the latest patch and I think they get rid of older versions furthermore they no longer have docker images anymore sadly.

A deal of this is ditto for Maven and Gradle but I assume those guys have reproducibility and if they don't the do not that would be far easier to host than the JDK (ie treat maven and gradle just like the other libraries in reproducible-central).

**Comment by hboutemy** [comment]
io.smallrye jandex is a small project that shows the issue: to be used to dig into the problem and try to find solutions

**Comment by hboutemy** [comment]
I just digged a little bit using https://github.com/tfij/Java-9-modules---the-simplest-example that just uses javac, without any build tool magic

running [`compile.sh`](https://github.com/tfij/Java-9-modules---the-simplest-example/blob/master/compile.sh) with JDK 11.0.2 and 11.0.16 gives me different `module-info.class`:
```
$ diffoscope build-11.0.*/pl.tfij.java9modules.app/*.class
--- build-11.0.16/pl.tfij.java9modules.app/module-info.class
+++ build-11.0.2/pl.tfij.java9modules.app/module-info.class
├── javap -verbose -constants -s -l -private {}
│ @@ -9,28 +9,28 @@
│  Constant pool:
│     #1 = Class              #9             // "module-info"
│     #2 = Utf8               SourceFile
│     #3 = Utf8               module-info.java
│     #4 = Utf8               Module
│     #5 = Module             #10            // "pl.tfij.java9modules.app"
│     #6 = Module             #11            // "java.base"
│ -   #7 = Utf8               11.0.16
│ +   #7 = Utf8               11.0.2
│     #8 = Module             #12            // "pl.tfij.java9modules.greetings"
│     #9 = Utf8               module-info
│    #10 = Utf8               pl.tfij.java9modules.app
│    #11 = Utf8               java.base
│    #12 = Utf8               pl.tfij.java9modules.greetings
│  {
│  }
│  SourceFile: "module-info.java"
│  Module:
│    #5,0                                    // "pl.tfij.java9modules.app"
│    #0
│    2                                       // requires
│      #6,8000                                 // "java.base" ACC_MANDATED
│ -    #7                                      // 11.0.16
│ +    #7                                      // 11.0.2
│      #8,0                                    // "pl.tfij.java9modules.greetings"
│      #0
│    0                                       // exports
│    0                                       // opens
│    0                                       // uses
│    0                                       // provides
```

I don't know if there is a way to compile without the `java.base` minor version, but it clearly will require an additional option at least

**Comment by hboutemy** [comment]
more details here https://issues.apache.org/jira/browse/MJAR-275?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17313902#comment-17313902

compiling with `--release 11` with some newer JDKs (tested with 16) avoid the JDK version to be stored

**Comment by hboutemy** [comment]
I created a focused test https://github.com/jvm-repo-rebuild/module-info
the behaviour is the same with JDK 11 to 21 EA: patch version is not stored only if compiling to a previous release

we'll need:
1. to report to JDK to have a fix
2. to post-process `module-info.class` to delete the unwanted value

**Comment by hboutemy** [comment]
Jira issue to have Maven workaround and patch the class created: https://issues.apache.org/jira/projects/MJAR/issues/MJAR-295
perhaps should better be moved from maven-jar-plugin to maven-compiler-plugin, we'll see
