### ISSUE TITLE
What determines the path of a package inside /content?

### ISSUE THREAD

**Issue by Vel1khan** [jvm-repo-rebuild/reproducible-central#116]
I'm currently performing some research on the reproducibility of packages and trying to automatically create the .buildspec files from a large dataset we extracted from Maven Central. However, for packages that this project has already created .buildspec files for, I would like to find them and use them instead of automatically generating them. I am having a hard time however, since it doesn't seem to be consistent with the package coordinates.

For example:
- com.github.spotbugs:spotbugs-maven-plugin is located in /content/com/github/spotbugs/spotbugs-maven-plugin
- org.apache.nifi:nifi is located in /content/org/apache/nifi/nifi

However:
- com.github.hazendaz.7zip:7zip is located in /content/com/github/7zip and not /content/com/github/7zip/7zip as would be expected
- org.apache.royale.compiler:compiler is located in /content/org/apache/royale/compiler

Is this by design and if so, how can I programmatically go from packageId:artifactId:version to the (possibly existing) path of the buildspec file?

**Comment by hboutemy** [comment]
yes, I did sometimes human simplification when directory names seemed redundant

I did not try to generate automatically, because there is a good chance that packages won't be reproducible initially because they did not even try to be, and even when they tried to be reproducible, they failed

don't generate too much noisy "this release is not reproducible" data, please, because that won't really help

what helps is to detect which packages tried to be reproducible, if they succeeded or not, and if not, if there is an easy fix or not

**Comment by hboutemy** [comment]
another thing that could be useful is automation of deriving a new release from an older one, adapting easy changes (like JDK release, or OS type, or ...), so it's easier to add the simple new releases

**Comment by Vel1khan** [comment]
Thanks a lot for the quick response. I'll just check for both paths. Good shout about the noisy data, I'll focus just on which are reproducible. If I find any that are not already here, I'll be sure to contribute to the project. Currently my dataset also contains whether packages have the build.outputTimestamp property, which narrows the search space significantly.

**Comment by hboutemy** [comment]
>  I'll focus just on which are reproducible. If I find any that are not already here, I'll be sure to contribute to the project
yes, these are the key aspects I follow for a few years now, and what really improves the situation: help will be welcome, because it's really a huge work

**Comment by hboutemy** [comment]
notice: when you provide a patch to a project that has a non-reproducible release listed here, don't hesitate to provide a patch to our buildspec pointing to the PR: that's a good way to track reproducibility improvement work done from release to release
