### ISSUE TITLE
README.md not fully updated by nightly update

### ISSUE THREAD

**Issue by pawellabaj** [jvm-repo-rebuild/reproducible-central#120]
I'm referring to [pl.com.labaj:auto-record](https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/pl/com/labaj/auto-record/README.md)

After I release next version of the library, the second row in the table has been added, but cells in _[build spec]_, _[result:reproducible?]_ and _[size]_ are empty.

Should I correct some files or this is the issue of nightly executed scripts?

**Comment by hboutemy** [comment]
during the first night, the update script discovers that a new release is available in Maven Central, then displays it

the day after (if I don't miss it), I sse the new release, then I try to reproduce it: this is only at the moment that the new buildspec is published

then on the next night, README is updated with rebuild results

the final result is partially automated, partially manual: at the end, you can see that your 2.0.0 release has been rebuilt (manually by me) and results published :)

**Comment by pawellabaj** [comment]
Thanks for the explanation

**Comment by pawellabaj** [comment]
Thanks for the explanation
