### ISSUE TITLE
Can the maven version affect reproducibility?

### ISSUE THREAD

**Issue by Vel1khan** [jvm-repo-rebuild/reproducible-central#121]
I scoured through the docs, the Apache Reproducibility guide, the wiki page and some of the issues on the Jira of the project, but I can't figure out whether the Maven version has an effect on the final checksums of the files. As far as I understand, only the Maven plugins have an effect, right? Why do some .buildspec files use different Maven versions? 

I'm trying to automate the creation of buildspec files, but I'm not sure whether I should just use the default Maven version or try multiple versions?

**Comment by Vel1khan** [comment]
Thanks a lot for the answer! Will investigate further.

**Comment by hboutemy** [comment]
Did you look ad `bin/wip.sh` script that i added recently? It's what it tries to do from a path to Maven Central, to ease initialization.

And there is the new "add.md" report to show new releases that look feasible, or old ones that would require some fixes: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/doc/add.md

**Comment by Vel1khan** [comment]
That is good to know, I didn't know about it. I have found a few packages that are not in content, will be adding their builspecs soon.
