### ISSUE TITLE
"Tool x JDK statistics" in README is not readable

### ISSUE THREAD

**Issue by Marcono1234** [jvm-repo-rebuild/reproducible-central#133]
The [section "Tool x JDK statistics" in the README](https://github.com/jvm-repo-rebuild/reproducible-central#tool-x-jdk-statistics) is not readable in the rendered form because it is displayed as a single paragraph instead of as plaintext table.

Maybe this can be solved by wrapping it in a Markdown code block (<code>\`\`\` ... \`\`\`</code>)?

**Comment by hboutemy** [comment]
the root cause is that the README.md page is too long now: GH markdown rendering is hard-cutting the output when something like 512kB are rendered
We need to change the layout to have a smaller first page
(I already had this issue in the past, before I went to 1 README.md per-project: Reproducible Central results are growing...)

**Comment by hboutemy** [comment]
= same as #80 in March 2022
the solution lasted for 1.5 years
perhaps it's time now for one README per LTD like org, com, ...

**Comment by Marcono1234** [comment]
I am not sure if the cause here is really that the README is too long. To me it looks rather like the formatting is incorrect (or missing).

For demonstration purposes, here are the first lines of this section:
```
<!-- BEGIN GENERATED STATS -->
     22 gradle     11
     26 mvn         7
   1025 mvn         8
      1 mvn         9
    836 mvn        11
```

And rendered:
> 
>     22 gradle     11
>     26 mvn         7
>   1025 mvn         8
>      1 mvn         9
>    836 mvn        11

This is the same broken formatting which can be seen on the README, except that there the text is all on a single line due to following more strictly the Markdown specification than the GitHub text fields here.

That was why I suggested to add <code>\`\`\`</code> around it (or alternatively convert it to a proper Markdown table):
````
<!-- BEGIN GENERATED STATS -->
```
     22 gradle     11
     26 mvn         7
   1025 mvn         8
      1 mvn         9
    836 mvn        11
```
````

And rendered:
> 
> ```
>     22 gradle     11
>     26 mvn         7
>   1025 mvn         8
>      1 mvn         9
>    836 mvn        11
> ```

**Comment by hboutemy** [comment]
ok, tested adding this formatting: I'm surprised, but it works and I prefer this simple fix :)
I'll add this markup to the generation script

**Comment by hboutemy** [comment]
I finally understood: everything was ok when the "mvn 8" statistic was up to 997 https://github.com/jvm-repo-rebuild/reproducible-central/tree/51e395815f2eb80d1e7194fd16f79c786eca689a
but when it went beyond 1000, it caused a missing space to detect the code block https://github.com/jvm-repo-rebuild/reproducible-central/tree/a3c1e8bd0024f5bb5c75fb370f35edb7663ae04d

thanks a lot for the feedback, I was looking in the wrong direction :)
