### ISSUE TITLE
create buildspec for QuickPerf 1.0.0-RC7

### ISSUE THREAD

**Issue by hboutemy** [jvm-repo-rebuild/reproducible-central#16]
released last WE https://github.com/quick-perf/quickperf/tree/release-1.0.0-RC7
should be reproducible given https://github.com/quick-perf/quickperf/pull/58

**Comment by nicokosi** [comment]
First attempt with @hboutemy during the Hackergarten Paris: QuickPerf 1.0.0-RC7's build is visibly not reproducible, the error is:
> [ERROR] Failed to execute goal on project quick-perf-junit5: Could not resolve dependencies for project org.quickperf:quick-perf-junit5:jar:1.0.0-RC7: Could not find artifact org.quickperf:quick-perf-junit5-test-util:jar:tests:1.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project quick-perf-junit5: Could not resolve dependencies for project org.quickperf:quick-perf-junit5:jar:1.0.0-RC7: Could not find artifact org.quickperf:quick-perf-junit5-test-util:jar:tests:1.0-SNAPSHOT

The full output is: [rebuild_quick-perf-1.0.0-RC7.txt](https://github.com/jvm-repo-rebuild/reproducible-central/files/5447790/rebuild_quick-perf-1.0.0-RC7.txt).

See Quick Perf issue https://github.com/quick-perf/quickperf/issues/126.

**Comment by hboutemy** [comment]
I was able to rebuild:
1. using the default profile instead of the release profile
2. modifying by hand the git checkout with `find wip/buildcache/quick-perf/ -name pom.xml -exec sed -i s/1.0-SNAPSHOT/1.0.0-RC7/g {} \;` (really bad trick, but the release is not independantly buildable...)

then I updated the buildspec to match detected reference environment: JDK 11 on Windows

rebuilding with these changes, I coud not reproduce the binary ouotput: it seems that with JDK 11, my trick to define `line.separator` to simulate Windows on my Linux box does not work, then generated `pom.properties` is not as expected...

at least, this time, the hard time to reproduce the build is not because of QuickPerf but because of limitations of the rebuild script when the reference release has been done on Windows. I don't know how to overcome these limitations :(

**Comment by hboutemy** [comment]
QuickPerf 1.0.0 is released: this time, it should be ok, if we have no additional surprise
@nicokosi ready to try? (eventually tuesday on Paris HackerGarten...)

**Comment by nicokosi** [comment]
Not available for the next Paris Hackergarten, sorry!

**Comment by nicokosi** [comment]
@hboutemy: My first attempt with QuickPerf 1.0.0 in https://github.com/jvm-repo-rebuild/reproducible-central/pull/47. 😭

**Comment by hboutemy** [comment]
QuickPerf 1.0.0 merged: thank you

as explained in #48 , this required additions in rebuild script that should be enhanced in the future
but at least IT WORKS!!!

thank you @nicokosi
