### ISSUE TITLE
Missing new versions in projects

### ISSUE THREAD

**Issue by jskov** [jvm-repo-rebuild/reproducible-central#184]
Hi

I noticed that the new versions of some of the dk.mada libraries are not checked.

For example https://github.com/jvm-repo-rebuild/reproducible-central/tree/master/content/dk/mada/jaxrs/openapi-jaxrs-client

Did something break in the Gradle checks?
(Did I break something?)

**Comment by hboutemy** [comment]
Hi @jskov ,
nothing broke: it's just that i run builds on new releases by hand
And honestly, when previous builds are not reproducible and I see no interest from project, I sometimes just stop trying to rebuild to get the exact same failure as previously :)
FYI, I have a list of new releases updated every day [doc/add.md](doc/add.md), I usually build new releases from previous releases that were successful, but on known issues from the past, I rebuild based on best effort and hope of usefulness of my efforts

you asked for openapi-jaxrs-client, then I just rebuilt the last release: and I got the improvement I did not expect any more
thanks for your interest (and help if you were involved in the build fix)

don't hesitate to point me to other good rebuild candidates

regards,

Hervé

**Comment by jskov** [comment]
Hi @hboutemy !

I am interested in keeping my projects reproducible.
Your project serves a very noble goal, IMO.
(and thanks a lot for putting in the work!)

But I had not noticed the breakage, because I just looked at the badges in my own projects.
I (wrongly) assumed they would alert me to problems.

Hence my [PR#183](https://github.com/jvm-repo-rebuild/reproducible-central/pull/183)  to start rectifying that problem.

If I can make some additional work (or changes) to help you accept it, please say so.
I would dearly like my badges to reflect the reality of your builds.


***PS:***
After I realized that the builds were broken, I tried to find out why (in mada-style-gradle).
I managed to reproduce the problem with 0.9.8 a few times, but as I got closer to an explanation, it started working.

If you try to reproduce the builds, they probably work now.

Seems to be somehow timing related. The javadoc generates some of the HTML statements in a different order sometimes.
And this causes the Gradle modules file to differ.

I will need to figure out the root cause (and fix it), or get the javadoc archive excluded from the modules file.
