### ISSUE TITLE
The component README.md can have broken links to modules

### ISSUE THREAD

**Issue by gemmellr** [jvm-repo-rebuild/reproducible-central#190]
The README.md for each component being rebuilt lists a count of how many modules it defines, and has an expandable set of links to the modules details on _central.sonatype.com_. These links are all use the latest rebuilt version in their URL GAV details, but seem to be for the aggregated set of modules from _all_ previously rebuilt releases. This means the links 404 if those modules no longer exist in the current release, e.g due to something being renamed or removed previously.

For example, see the [artemis README.md](https://github.com/jvm-repo-rebuild/reproducible-central/blob/d75f36910acdb08e5bb6a712a71ece4e47d48d12/content/org/apache/activemq/artemis/README.md) following addition of 2.36.0. It indicates "This project defines 218 modules:" and expands to links for them, all at version 2.36.0. The first 150+ links all 404 because they are for examples that dont exist in recent versions of the build, having previously moved out to their own repository/build (and no longer being deployed). There are multiple other later links that similarly 404 for modules that were either renamed or simply deleted in the past.

Feels like the module links should only exist for the latest version modules (or else use the latest version they actually existed for, so they are functional links)?

**Comment by hboutemy** [comment]
good catch, good idea
code is https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/bin/update-reproducibility-summary.sh#L125

**Comment by gemmellr** [comment]
I have raised a draft PR #195 with a potential update to the script, and the effects of running it.

**Comment by gemmellr** [comment]
I updated and removed draft status on the PR last week. Thought I had mentioned it here at the time, but seems I only did it on the PR itself.

**Comment by hboutemy** [comment]
see result https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/activemq/artemis/README.md
