### ISSUE TITLE
Support for Maven toolchain builds that need a (single) non-LTS JDK

### ISSUE THREAD

**Issue by nielsbasjes** [jvm-repo-rebuild/reproducible-central#199]
This should having a build with something like

   jdk=21
   toolchains="8|17|21|22"

or

   jdk=22
   toolchains="8|17|21|22"

Note: I'm working on this.

**Comment by nielsbasjes** [comment]
My current attempt https://github.com/jvm-repo-rebuild/reproducible-central/pull/200 does not work correctly yet.

**Comment by hboutemy** [comment]
@nielsbasjes would Azul Debian packages be an option to easily add any non-LTS in a Debian-aware way?

see https://hub.docker.com/r/azul/zulu-openjdk-debian for the list of versions: really wide

and https://github.com/zulu-openjdk/zulu-openjdk/blob/master/debian/22-latest/Dockerfile for their way to install: I don't know if it updates default JVM...

**Comment by nielsbasjes** [comment]
That looks promising.
Key question is if we can easily install additional jdks and generate a valid toolchains config based on this.

**Comment by hboutemy** [comment]
you are the only one interested in toolchains: I'm focusing on basic mono-JDK build = the vast majority
but it's true that you could also use it for your toolchains-oriented images

on generating a toolchains config from many JDKs available in a context, honestly, there are many ways to do it, and even a recent magic addition: https://maven.apache.org/plugins/maven-toolchains-plugin/generate-jdk-toolchains-xml-mojo.html, with associated explanations https://maven.apache.org/plugins/maven-toolchains-plugin/toolchains/jdk-discovery.html
