### ISSUE TITLE
create buildspec for dropwizard 2.0.11 & 2.0.12

### ISSUE THREAD

**Issue by hboutemy** [jvm-repo-rebuild/reproducible-central#22]
io.dropwizard:dropwizard-project:2.0.11

buildspec probably quite similar to release 2.0.10: let's hope build result reproducibility has improved on the last non-reproducible artifact

**Comment by bhamail** [comment]
I started looking into creating updated specs, but first I tried to run the "old" 2.0.10 spec and am seeing errors during the git clone:

```
$ ./rebuild.sh content/io/dropwizard/core/dropwizard-2.0.10.buildspec 
Rebuilding from spec content/io/dropwizard/core/dropwizard-2.0.10.buildspec
- groupId: io.dropwizard
- artifactId: dropwizard-core
- version: 2.0.10
- gitRepo: https://github.com/dropwizard/dropwizard.git
- gitTag: v2.0.10
- tool: mvn
- jdk: 8
- newline: lf
- command: mvn clean package -DskipTests
- buildinfo: dropwizard-archetypes/java-simple/target/java-simple-2.0.10.buildinfo
Cloning into 'dropwizard-core'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (17/17), done.
error: object 6fbf9def0293986beb2547a671f46148a5d2faf7: badDate: invalid author/committer line - bad date
fatal: fsck error in packed object
fatal: index-pack failed
fatal: failed to clone dropwizard-core
```

Not finding a lot searching for solutions. Does this ring a bell for anyone?

**Comment by bhamail** [comment]
I'm seeing the same error as shown above in all the dropwizard projects. Googling seems to indicate a corruption issue in the git history. Not sure how best to proceed.

**Comment by hboutemy** [comment]
@bhamail if your local Git clone is corrupted, just delete it: it's cloned in the `cache` directory that is created near the buildspec

**Comment by bhamail** [comment]
> @bhamail if your local Git clone is corrupted, just delete it: it's cloned in the `cache` directory that is created near the buildspec

Actually, the info I found indicates the corruption exists in the original repository (so creating a new clone will just include the same corruption). I'm looking into creating a "skipList" as described here: https://github.blog/2015-09-29-git-2-6-including-flexible-fsck-and-improved-status/

**Comment by bhamail** [comment]
FYI, in case it helps, I found a workaround for the issues I was seeing during `git clone` caused by "badDate" objects in the origin repository. In case it is useful, I'll try to push branch with an approach similar to what I used in PR #38

**Comment by bhamail** [comment]
FWIW, here's a PR based on the one from @dialaya, which deals with the original repo corruption issue.
https://github.com/jvm-repo-rebuild/reproducible-central/pull/39
