### ISSUE TITLE
Reproducible Builds Badge - anchor

### ISSUE THREAD

**Issue by slawekjaranowski** [jvm-repo-rebuild/reproducible-central#51]
In README we heve example:

```
[![Reproducible Builds](https://img.shields.io/badge/Reproducible_Builds-ok-green?labelColor=blue)](https://github.com/jvm-repo-rebuild/reproducible-central#...groupId...:...artifactId...)
```

Where anchor is: `#...groupId...:...artifactId...`
But on rendered README on GitHub we have: `#user-content-groupId:artifactId`

Which one should be used and why we have inconsistent.

**Comment by hboutemy** [comment]
uh, I never saw that: I don't know which magic happens in GitHub rendered page but I tested and the link without the `user-content-` prefix works
see for example https://github.com/apache/maven-war-plugin

**Comment by slawekjaranowski** [comment]
it is some magic for me ... once works and once not

**Comment by hboutemy** [comment]
> once works and once not

I never had such intermittent result
