### ISSUE TITLE
choose Maven version in buildspec when necessary

### ISSUE THREAD

**Issue by hboutemy** [jvm-repo-rebuild/reproducible-central#69]
seen with Apache Dubbo 3.0.5: Maven < 3.6.3 required because flatten-maven-plugin uses root pom and https://issues.apache.org/jira/browse/MNG-6778

then we need to specify in buildspec not only `mvn` but `mvn-3.6.1` to force Maven version used by `rebuild.sh`

**Comment by hboutemy** [comment]
Mina ftp-server 1.4.1 has "allowed range (3.8,]"

**Comment by io7m** [comment]
I'm running into this on my own projects as well. I currently enforce using Maven versions in the range `[3.8.2,4.0.0)`.

`fatal: build tool not yet supported: mvn-3.8.2`
