### ISSUE TITLE
non reproducible Include-Resource OSGi entries

### ISSUE THREAD

**Issue by hboutemy** [jvm-repo-rebuild/reproducible-central#99]
a lot of reproduciblity efforts have been done for OSGi bundle, both at Felix maven-bundle-plugin and at Bnd levels: with maven-bundle-plugin 5.1.5 (fixed [FELIX-6496](https://issues.apache.org/jira/browse/FELIX-6496)) that uses Bnd 6.2 (fixes [#5021](https://github.com/bndtools/bnd/issues/5021)), OSGi bundles should be reproducible

The fact is that it's not always the case: quite often, we get non-reproducible "Include-Resource: list of paths" entries

Issue [FELIX-6602](https://issues.apache.org/jira/browse/FELIX-6602) created

We need to find where the issue comes from: as a first analysis, these files are resources described in pom.xml resources https://maven.apache.org/ref/3.8.6/maven-model/maven.html#class_resource , we need to track how order of resource entries and files found in each entry is kept...

**Comment by ao-apps** [comment]
We are also seeing this issue in `Export-Package` and `Include-Resource`.

I don't know if it's related, but we declare `Include-Resources` as:

```
<Include-Resource>
  {maven-resources},
  ${bundle.resources-filtered}
</Include-Resource>
```

**Comment by hboutemy** [comment]
I suppose `{maven-resources}` means what comes from Maven's `project.build.resources`, and yes, I suppose Maven does not guarantee an order
I imagine it would be OSGi tool to order the resources when dumping into `<Include-Resource>`: I suppose it's Bnd's role...

**Comment by hboutemy** [comment]
MyBatis https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/mybatis/mybatis/README.md could be a good project to investigate, given it's mono-module build

**Comment by hboutemy** [comment]
PR created https://github.com/apache/felix-dev/pull/208

**Comment by hboutemy** [comment]
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/antlr/antlr4/antlr4-master-4.12.0.diffoscope

**Comment by hboutemy** [comment]
maven-bundle-plugin 5.1.9 vote in progress https://lists.apache.org/thread/lcnljdcg1ls8hg1kyk5lnh31kv594t3n

**Comment by hboutemy** [comment]
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/dropwizard/metrics/README.md
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/dropwizard/metrics5/README.md
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/activemq/README.md

**Comment by hboutemy** [comment]
maven-bundle-plugin 5.1.9 available: projects now just need to upgrade
